version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: price_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cnlg_be
    ports:
      - "54328:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: price_tracker_app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:54328/cnlg_be
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: