"""add thumbnail_url and weekly_quota to models

Revision ID: 50453611d430
Revises: e999a4262c33
Create Date: 2026-04-21 11:12:40.932481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50453611d430'
down_revision: Union[str, Sequence[str], None] = 'e999a4262c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('weekly_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('requests_this_week', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_quota_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_quota_reset')
    op.drop_column('users', 'requests_this_week')
    op.drop_column('users', 'weekly_quota')
    op.drop_column('products', 'thumbnail_url')
    # ### end Alembic commands ###
