"""rename url to product_id and remove unique constraint

Revision ID: e7a5813197e1
Revises: 50453611d430
Create Date: 2026-04-21 14:20:59.903508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a5813197e1'
down_revision: Union[str, Sequence[str], None] = '50453611d430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('products_url_key'), 'products', type_='unique')
    op.drop_column('products', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('products_url_key'), 'products', ['url'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'product_id')
    # ### end Alembic commands ###
